### ISSUE TITLE
Is this going to be continued?

### ISSUE THREAD

**Issue by Timple** [dalehamel/rasplex-build#1]
On the rasplex website it is mentioned that a raspbian port already exists. However this is the only mention of raspbian I could find on github.

**Comment by dalehamel** [comment]
Where on the website does it mention this?

**Comment by Timple** [comment]
Right here:

http://www.rasplex.com/about/what-is-rasplex.html

First result if I google rasplex + raspbian

2014-10-06 20:19 GMT+02:00 Dale Hamel notifications@github.com:

> Where on the website does it mention this?
>

**Comment by dalehamel** [comment]
AFAIK there has never been a working raspbian port of rasplex, not sure how
that got on the site.
